{{- if and .Values.cyberpunk.enabled .Values.cyberpunk.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-cyberpunk
  labels:
    app.kubernetes.io/name: {{ include "fuinjutsu.name" . }}-cyberpunk
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-cyberpunk
  minReplicas: {{ .Values.cyberpunk.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.cyberpunk.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.cyberpunk.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.cyberpunk.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.cyberpunk.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.cyberpunk.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}