{{- if and .Values.mcp.enabled .Values.mcp.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-mcp
  labels:
    app.kubernetes.io/name: {{ include "fuinjutsu.name" . }}-mcp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-mcp
  minReplicas: {{ .Values.mcp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.mcp.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.mcp.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mcp.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.mcp.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.mcp.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}