{{- if and .Values.apiKeys.create (not .Values.apiKeys.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-keys
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.apiKeys.keys }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}