{{- if .Values.proxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app.kubernetes.io/name: {{ include "fuinjutsu.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fuinjutsu.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}